apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: ocp-keycloak
  labels:
    app: ocp
spec:
  instances: 1
  extensions:
    - >-
      https://github.com/aerogear/keycloak-metrics-spi/releases/download/1.0.4/keycloak-metrics-spi-1.0.4.jar
  externalAccess:
    enabled: false
---
apiVersion: keycloak.org/v1alpha1
kind: KeycloakRealm
metadata:
  name: ocp-realm
  labels:
    app: ocp
spec:
  realm:
    id: ocp
    realm: ocp
    enabled: true
    displayName: OCP Realm
  instanceSelector:
    matchLabels:
      app: ocp      