apiVersion: k8s.nginx.org/v1alpha1
kind: NginxIngressController
metadata:
  namespace: nginx-demo
  name: my-nginx-ingress-controller
spec:
  ingressClass: nginx
  serviceType: LoadBalancer
  nginxPlus: false
  type: deployment
  enableCRDs: false
  image:
    pullPolicy: Always
    repository: docker.io/nginx/nginx-ingress
    tag: 1.9.1-ubi
  replicas: 1
