apiVersion: v1
kind: ConfigMap
metadata:
  name: pacman-cm
  namespace: pacman-dev-web
data:
  pacman.conf: |-
    server {
            listen 8080;

            access_log /var/log/nginx/access.log;
            error_log /var/log/nginx/error.log;

            location / {
                proxy_pass                          http://pacman.pacman-dev-app.svc:8080/;
                proxy_set_header Host               $host;
                proxy_set_header X-Real-IP          $remote_addr;
                proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
            }
        }
