apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-from-other-namespaces-except-web
  namespace: pacman-dev-app
spec:
  podSelector: {}
  ingress:
  - from:
     - namespaceSelector:
        matchLabels:
          name: pacman-dev-web