apiVersion: v1
kind: Service
metadata:
  name: pacman
  namespace: pacman-dev-app
  labels:
    name: pacman
    app.kubernetes.io/name: pacman
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    name: pacman
    app.kubernetes.io/name: pacman
